/**
 * @file EpPlacementPointActionType.js
 */

/**
 * 获取所有的 Ep Placement Point
 */
export const GET_EP_PLACEMENT_POINT_REQUEST = 'GET_EP_PLACEMENT_POINT_REQUEST';
export const GET_EP_PLACEMENT_POINT_SUCCESS = 'GET_EP_PLACEMENT_POINT_SUCCESS';
export const GET_EP_PLACEMENT_POINT_FAILURE = 'GET_EP_PLACEMENT_POINT_FAILURE';
